##Importing and Base Model

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
import tensorflow as tf
import h5py
import cv2
import keras
import numpy as np
from keras.datasets import mnist
from tensorflow.keras.applications.vgg19 import preprocess_input
from tensorflow.keras.utils import to_categorical

In [ ]:
#loading and preprocessing MNIST
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 1s 0us/step


In [ ]:
#normalizing the Data
X= x_train/255
x_test= x_test/255



In [ ]:
X.shape

(60000, 28, 28)

In [ ]:
# Define the model
model = keras.Sequential([
           keras.layers.Flatten(input_shape=(28,28)),
           keras.layers.Dense(8,activation = 'relu'),
           keras.layers.Dense(16, activation = 'relu'),
           keras.layers.Dense(10,activation= 'softmax')
                            ])
#compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
model.fit(X, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 10s 3ms/step - loss: 0.5722 - accuracy: 0.8239
Epoch 2/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.3092 - accuracy: 0.9092
Epoch 3/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2770 - accuracy: 0.9191
Epoch 4/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2582 - accuracy: 0.9241
Epoch 5/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2489 - accuracy: 0.9276
Epoch 6/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2399 - accuracy: 0.9301
Epoch 7/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2350 - accuracy: 0.9316
Epoch 8/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2290 - accuracy: 0.9337
Epoch 9/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2250 - accuracy: 0.9342
Epoch 10/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.22

##Question 1

In [ ]:
old_loss, old_acc = model.evaluate(x_test, y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.2314 - accuracy: 0.9343


In [ ]:
# Save the weights
model.save_weights('my_model_weights.h5')

In [ ]:
# Load the weights
model.load_weights('my_model_weights.h5')

In [ ]:
# Get the current weights
ogweights = model.get_weights()

In [ ]:
# Set any weights less than 0 to 0 and any weights greater than 0 to 1
new_weights0 = [np.where(w < 0, 0, 1) for w in ogweights]

In [ ]:
# Set the new weights
model.set_weights(new_weights0)

In [ ]:
for w in ogweights:
  print(w)

[[-0.03159413 -0.06214216  0.08517782 ... -0.07799149  0.06888369
   0.00113956]
 [ 0.02584756 -0.04461527 -0.04302752 ... -0.07847926  0.08251494
  -0.0828396 ]
 [-0.06120673 -0.05895248 -0.07485    ... -0.00985698 -0.02898942
  -0.01278915]
 ...
 [-0.00822426 -0.0793654   0.08328699 ...  0.05069119  0.05061263
  -0.04832891]
 [-0.00314463 -0.04941131 -0.01194549 ...  0.08203328 -0.03172798
  -0.02527577]
 [-0.01591643 -0.0565291  -0.06027625 ... -0.08654116  0.03693574
  -0.04287132]]
[ 0.27755988  0.37061834 -0.15812984  0.13914852  0.29569384  0.2272889
  0.01819601  0.07710867]
[[ 4.70321596e-01 -1.33464962e-01  6.62703991e-01  3.96862507e-01
  -9.38432589e-02  6.80372477e-01  2.28520289e-01  5.05725980e-01
  -5.01406565e-03  4.83847409e-01  1.75680950e-01  1.06978774e-01
  -3.37554604e-01 -5.68998337e-01  7.14039207e-01 -2.33535185e-01]
 [ 6.54727817e-01 -6.28179550e-01 -6.32104993e-01  5.22172511e-01
   7.39932716e-01  1.63301766e-01 -2.09055901e-01 -1.91811308e-01
  -3.73205245

In [ ]:
for w in new_weights0:
  print(w)

[[0 0 1 ... 0 1 1]
 [1 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 1 1 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]]
[1 1 0 1 1 1 1 1]
[[1 0 1 1 0 1 1 1 0 1 1 1 0 0 1 0]
 [1 0 0 1 1 1 0 0 0 1 0 1 0 0 0 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1]
 [0 1 1 1 1 0 0 1 0 0 1 0 1 0 0 1]
 [1 1 1 1 0 1 1 0 0 1 0 1 1 1 1 1]
 [1 1 0 0 0 0 0 0 1 0 0 1 1 0 0 0]
 [0 1 0 0 1 1 0 0 0 1 1 0 0 1 1 0]
 [1 1 1 1 1 1 0 0 0 0 1 0 1 1 0 1]]
[1 0 0 1 1 1 0 1 1 0 0 0 1 1 1 0]
[[0 0 0 0 0 0 0 1 0 1]
 [1 0 0 1 1 0 1 0 0 1]
 [0 0 0 0 1 0 0 1 1 1]
 [0 1 0 1 0 1 0 1 1 1]
 [1 1 1 1 0 1 1 0 1 1]
 [1 0 1 0 1 1 0 1 1 0]
 [0 0 1 1 1 0 0 1 0 1]
 [1 1 0 0 1 0 1 1 0 0]
 [0 1 1 1 0 1 1 1 0 0]
 [0 0 1 1 0 0 0 1 0 1]
 [1 0 0 1 0 1 0 0 1 0]
 [0 1 1 1 0 0 1 0 0 1]
 [0 0 0 0 1 1 1 0 0 0]
 [0 0 0 1 1 1 0 0 1 1]
 [0 1 0 1 1 0 0 1 0 1]
 [0 0 1 0 1 0 1 0 1 0]]
[0 1 1 0 1 1 0 1 0 0]


In [ ]:
model.set_weights(ogweights)


In [ ]:
model.set_weights(new_weights0)
new_loss0, new_acc0 = model.evaluate(x_test,y_test)

313/313 [==============================] - 1s 2ms/step - loss: 756.6269 - accuracy: 0.1009


##Question 2

In [ ]:
# Set any weights less than 0 to -1 and any weights greater than 0 to 1
new_weights1 = [np.where(w < 0, -1, 1) for w in ogweights]

In [ ]:
for w in new_weights1:
  print(w)

[[-1 -1  1 ... -1  1  1]
 [ 1 -1 -1 ... -1  1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 ...
 [-1 -1  1 ...  1  1 -1]
 [-1 -1 -1 ...  1 -1 -1]
 [-1 -1 -1 ... -1  1 -1]]
[ 1  1 -1  1  1  1  1  1]
[[ 1 -1  1  1 -1  1  1  1 -1  1  1  1 -1 -1  1 -1]
 [ 1 -1 -1  1  1  1 -1 -1 -1  1 -1  1 -1 -1 -1 -1]
 [-1 -1  1  1  1  1  1  1  1  1  1  1 -1  1  1  1]
 [-1  1  1  1  1 -1 -1  1 -1 -1  1 -1  1 -1 -1  1]
 [ 1  1  1  1 -1  1  1 -1 -1  1 -1  1  1  1  1  1]
 [ 1  1 -1 -1 -1 -1 -1 -1  1 -1 -1  1  1 -1 -1 -1]
 [-1  1 -1 -1  1  1 -1 -1 -1  1  1 -1 -1  1  1 -1]
 [ 1  1  1  1  1  1 -1 -1 -1 -1  1 -1  1  1 -1  1]]
[ 1 -1 -1  1  1  1 -1  1  1 -1 -1 -1  1  1  1 -1]
[[-1 -1 -1 -1 -1 -1 -1  1 -1  1]
 [ 1 -1 -1  1  1 -1  1 -1 -1  1]
 [-1 -1 -1 -1  1 -1 -1  1  1  1]
 [-1  1 -1  1 -1  1 -1  1  1  1]
 [ 1  1  1  1 -1  1  1 -1  1  1]
 [ 1 -1  1 -1  1  1 -1  1  1 -1]
 [-1 -1  1  1  1 -1 -1  1 -1  1]
 [ 1  1 -1 -1  1 -1  1  1 -1 -1]
 [-1  1  1  1 -1  1  1  1 -1 -1]
 [-1 -1  1  1 -1 -1 -1  1 -1  1]
 [ 1 -1 -1  1 -1  1 -1 -1  1 

In [ ]:
model.set_weights(new_weights1)
new_loss1, new_acc1 = model.evaluate(x_test,y_test)

313/313 [==============================] - 1s 3ms/step - loss: 116.6102 - accuracy: 0.3537


##Question 3

In [ ]:
#converting all float type weights to type int
new_weightsint = [w.astype(np.int32) for w in ogweights]

In [ ]:
for w in new_weightsint:
  print(w)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[0 0 0 0 0 0 0 0]
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 -1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0 -1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 -1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 -1  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 -1]
 [ 0  0  0  0  0  0 -1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 

In [ ]:
model.set_weights(new_weightsint)
new_lossint, new_accint = model.evaluate(x_test,y_test)

313/313 [==============================] - 1s 4ms/step - loss: 2.3719 - accuracy: 0.0892


##Question 4

In [ ]:
model.set_weights(ogweights)

In [ ]:
# Convert the model weights to a list of numpy arrays
weights_list = [x.numpy() for x in model.weights]

# Quantize the weights
new_weightsquant = []
for weight in weights_list:
    max_val = np.abs(weight).max()
    scale = max_val / ((2 ** 8) - 1)
    quant_weight = np.round(weight / scale).astype(np.int8)
    new_weightsquant.append(quant_weight * scale)

In [ ]:
# During runtime, compute the weights values
runtime_weights = [w/scale for w in quant_weight]

In [ ]:
for w in quant_weight:
  print(w)

103
102
94
-83
99
-1
-4
62
47
59


In [ ]:
# Set the quantized weights on the model
model.set_weights(new_weightsquant)

In [ ]:
# Evaluate the model on test data to get loss and accuracy
new_lossquant, new_accquant = model.evaluate(x_test,y_test)


313/313 [==============================] - 1s 2ms/step - loss: 9.7719 - accuracy: 0.0773


##Results

In [ ]:
print('Old loss:', old_loss, 'Old accuracy:', old_acc)
print('New loss with 0:', new_loss0, 'New accuracy with 0:', new_acc0)
print('New loss with -1:', new_loss1, 'New accuracy with -1:', new_acc1)
print('New loss with typecast:', new_lossint, 'New accuracy with typecast:', new_accint)
print('New loss with Quantisation:', new_lossquant, 'New accuracy with quantization:', new_accquant)

Old loss: 0.23142068088054657 Old accuracy: 0.9343000054359436
New loss with 0: 756.6268920898438 New accuracy with 0: 0.10090000182390213
New loss with -1: 116.61021423339844 New accuracy with -1: 0.35370001196861267
New loss with typecast: 2.371941566467285 New accuracy with typecast: 0.08919999748468399
New loss with Quantisation: 9.771871566772461 New accuracy with quantization: 0.07729999721050262
